### ISSUE TITLE
Update README and/or archive this repo?

### ISSUE THREAD

**Issue by xuwei-k** [scala-steward-org/repos#1029]
https://twitter.com/fst9000/status/1532088018084978689

> My public Scala Steward instance is not running anymore. I've turned it off to focus my attention and energy on other matters.

🤔

**Comment by exoego** [comment]
Thanks for raising.
Will discuss within maintainers.

**Comment by xuwei-k** [comment]
https://contributors.scala-lang.org/t/can-scala-maintain-a-public-scala-steward-instance/5754

**Comment by xuwei-k** [comment]
- https://github.com/scala-steward-org/scala-steward/pull/2621

**Comment by fthomas** [comment]
👍 for updating the README and archiving this repo.
