### ISSUE TITLE
Support bitbucket

### ISSUE THREAD

**Issue by mslinn** [scala-steward-org/repos#467]
How about enhancing the `repos.md` syntax to include an optional prefix for the git host on the public `scala-steward` instance?
For example:
```
- mslinn/awslib_scala  # defaults to github
- github:mslinn/dottyTemplate
- bitbucket:mslinn/myProject
- gitlab:mslinn/MyProject
```

**Comment by fthomas** [comment]
Scala Steward can now update projects on Bitbucket. Just add your projects to https://github.com/scala-steward-org/repos/blob/master/repos-bitbucket.md.

Btw, the following options are required for Bitbucket:
```
  --vcs-type bitbucket
  --vcs-api-host "https://api.bitbucket.org/2.0"
```
